name: Deploy Context Editor to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'examples/context-editor/package-lock.json'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: |
          cd examples/context-editor
          npm ci
      - name: Build
        env:
          PUBLIC_URL: https://agentic-insights.github.io/codebase-context-spec/
        run: |
          cd examples/context-editor
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples/context-editor/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4